#!/usr/bin/env python

import sys
import copy
import time
import rospy

import numpy as np
from lab5_header import *
from lab5_func import *
from blob_search import *

# ========================= Student's code starts here =========================

#Position for UR3 not blocking the camera
go_away = [270*PI/180.0, -90*PI/180.0, 90*PI/180.0,
           -90*PI/180.0, -90*PI/180.0, 135*PI/180.0]

#Store world coordinates of green and yellow blocks
xw_yw_G = []
xw_yw_Y = []

#Defined drop-off coordinates
DROP_GREEN  = [0.30, -0.15, 0.02]
DROP_YELLOW = [0.30,  0.15, 0.02]

# Any other global variable you want to define, such as pick height, safe height
BLOCK_Z     = 0.02
SAFE_Z      = 0.15

# ========================= Student's code ends here ===========================

################ Pre-defined parameters and functions no need to change below ################

# 20Hz
SPIN_RATE = 20

# UR3 home location
home = [0*PI/180.0, 0*PI/180.0, 0*PI/180.0, 0*PI/180.0, 0*PI/180.0, 0*PI/180.0]

# UR3 current position, using home position for initialization
current_position = copy.deepcopy(home)

thetas = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

digital_in_0 = 0
analog_in_0 = 0.0

suction_on = True
suction_off = False

current_io_0 = False
current_position_set = False

image_shape_define = False


"""
Whenever ur3/gripper_input publishes info this callback function is called.
"""
def input_callback(msg):

    global digital_in_0
    digital_in_0 = msg.DIGIN
    digital_in_0 = digital_in_0 & 1 # Only look at least significant bit, meaning index 0


"""
Whenever ur3/position publishes info, this callback function is called.
"""
def position_callback(msg):

    global thetas
    global current_position
    global current_position_set

    thetas[0] = msg.position[0]
    thetas[1] = msg.position[1]
    thetas[2] = msg.position[2]
    thetas[3] = msg.position[3]
    thetas[4] = msg.position[4]
    thetas[5] = msg.position[5]

    current_position[0] = thetas[0]
    current_position[1] = thetas[1]
    current_position[2] = thetas[2]
    current_position[3] = thetas[3]
    current_position[4] = thetas[4]
    current_position[5] = thetas[5]

    current_position_set = True


"""
Function to control the suction cup on/off
"""
def gripper(pub_cmd, loop_rate, io_0):

    global SPIN_RATE
    global thetas
    global current_io_0
    global current_position

    error = 0
    spin_count = 0
    at_goal = 0

    current_io_0 = io_0

    driver_msg = command()
    driver_msg.destination = current_position
    driver_msg.v = 1.0
    driver_msg.a = 1.0
    driver_msg.io_0 = io_0
    pub_cmd.publish(driver_msg)

    while(at_goal == 0):

        if( abs(thetas[0]-driver_msg.destination[0]) < 0.0005 and \
            abs(thetas[1]-driver_msg.destination[1]) < 0.0005 and \
            abs(thetas[2]-driver_msg.destination[2]) < 0.0005 and \
            abs(thetas[3]-driver_msg.destination[3]) < 0.0005 and \
            abs(thetas[4]-driver_msg.destination[4]) < 0.0005 and \
            abs(thetas[5]-driver_msg.destination[5]) < 0.0005 ):

            #rospy.loginfo("Goal is reached!")
            at_goal = 1

        loop_rate.sleep()

        if(spin_count >  SPIN_RATE*5):

            pub_cmd.publish(driver_msg)
            rospy.loginfo("Just published again driver_msg")
            spin_count = 0

        spin_count = spin_count + 1

    return error


"""
Move robot arm from one position to another
"""
def move_arm(pub_cmd, loop_rate, dest, vel, accel):

    global thetas
    global SPIN_RATE

    error = 0
    spin_count = 0
    at_goal = 0

    driver_msg = command()
    driver_msg.destination = dest
    driver_msg.v = vel
    driver_msg.a = accel
    driver_msg.io_0 = current_io_0
    pub_cmd.publish(driver_msg)

    loop_rate.sleep()

    while(at_goal == 0):

        if( abs(thetas[0]-driver_msg.destination[0]) < 0.0005 and \
            abs(thetas[1]-driver_msg.destination[1]) < 0.0005 and \
            abs(thetas[2]-driver_msg.destination[2]) < 0.0005 and \
            abs(thetas[3]-driver_msg.destination[3]) < 0.0005 and \
            abs(thetas[4]-driver_msg.destination[4]) < 0.0005 and \
            abs(thetas[5]-driver_msg.destination[5]) < 0.0005 ):

            at_goal = 1
            #rospy.loginfo("Goal is reached!")

        loop_rate.sleep()

        if(spin_count >  SPIN_RATE*5):

            pub_cmd.publish(driver_msg)
            rospy.loginfo("Just published again driver_msg")
            spin_count = 0

        spin_count = spin_count + 1

    return error

################ Pre-defined parameters and functions no need to change above ################


def move_block(pub_cmd, loop_rate, start_xw_yw_zw, target_xw_yw_zw, vel, accel):

    """
    start_xw_yw_zw: (x, y, z) of block pickup in world coordinates
    target_xw_yw_zw: (x, y, z) of block drop-off in world coordinates
    """

    global suction_on, suction_off, digital_in_0

    error = 0

    # ----------------- Extract coords -----------------
    sx, sy, sz = start_xw_yw_zw   # pick location
    tx, ty, tz = target_xw_yw_zw  # drop location

    SAFE_Z = 0.15        # safe hover height
    PICK_Z = sz          # usually ~0.02 m
    PLACE_Z = tz         # usually ~0.02 m

    # ----------------- IK for joint targets -----------------
    # Above pick
    q_above_pick = lab_invk(sx, sy, SAFE_Z, 0)
    # Pick
    q_pick = lab_invk(sx, sy, PICK_Z, 0)

    # Above place
    q_above_place = lab_invk(tx, ty, SAFE_Z, 0)
    # Place
    q_place = lab_invk(tx, ty, PLACE_Z, 0)

    # ----------------- Motion sequence -----------------

    # 1. Move above pickup location
    error = move_arm(pub_cmd, loop_rate, q_above_pick, vel, accel)
    if error != 0: return error

    # 2. Move down to pickup
    error = move_arm(pub_cmd, loop_rate, q_pick, vel/2, accel/2)
    if error != 0: return error

    # 3. Turn suction ON
    gripper(pub_cmd, loop_rate, suction_on)
    time.sleep(0.5)

    # Suction feedback check (pickup)
    if digital_in_0 != 1:
        rospy.logerr("Suction error: No block detected at pickup!")
        gripper(pub_cmd, loop_rate, suction_off)
        return 2

    # 4. Lift block
    error = move_arm(pub_cmd, loop_rate, q_above_pick, vel, accel)
    if error != 0: return error

    # 5. Move above placement
    error = move_arm(pub_cmd, loop_rate, q_above_place, vel, accel)
    if error != 0: return error

    # 6. Move down to placement
    error = move_arm(pub_cmd, loop_rate, q_place, vel/2, accel/2)
    if error != 0: return error

    # 7. Release block
    gripper(pub_cmd, loop_rate, suction_off)
    time.sleep(0.5)

    # Suction feedback check (release)
    if digital_in_0 != 0:
        rospy.logerr("Suction error: Block still attached after release!")
        return 3

    # 8. Lift up again
    error = move_arm(pub_cmd, loop_rate, q_above_place, vel, accel)
    if error != 0: return error

    return error



class ImageConverter:

    def __init__(self, SPIN_RATE):

        self.bridge = CvBridge()
        self.image_pub = rospy.Publisher("/image_converter/output_video", Image, queue_size=10)
        self.image_sub = rospy.Subscriber("/cv_camera_node/image_raw", Image, self.image_callback)
        self.loop_rate = rospy.Rate(SPIN_RATE)

        # Check if ROS is ready for operation
        while(rospy.is_shutdown()):
            print("ROS is shutdown!")


    def image_callback(self, data):

        global xw_yw_G # store found green blocks in this list
        global xw_yw_Y # store found yellow blocks in this list

        try:
          # Convert ROS image to OpenCV image
            raw_image = self.bridge.imgmsg_to_cv2(data, "bgr8")
        except CvBridgeError as e:
            print(e)

        cv_image = cv2.flip(raw_image, -1)
        cv2.line(cv_image, (0,50), (640,50), (0,0,0), 5)

        # You will need to call blob_search() function to find centers of green blocks
        # and yellow blocks, and store the centers in xw_yw_G & xw_yw_Y respectively.

        # If no blocks are found for a particular color, you can return an empty list,
        # to xw_yw_G or xw_yw_Y.

        # Remember, xw_yw_G & xw_yw_Y are in global coordinates, which means you will
        # do coordinate transformation in the blob_search() function, namely, from
        # the image frame to the global world frame.

        xw_yw_G = blob_search(cv_image, "green")
        xw_yw_Y = blob_search(cv_image, "yellow")


"""
Program run from here
"""
def main():

    global go_away
    global xw_yw_Y
    global xw_yw_G

    # global variable1
    # global variable2

    # Initialize ROS node
    rospy.init_node('lab5node')

    # Initialize publisher for ur3/command with buffer size of 10
    pub_command = rospy.Publisher('ur3/command', command, queue_size=10)

    # Initialize subscriber to ur3/position & ur3/gripper_input and callback fuction
    # each time data is published
    sub_position = rospy.Subscriber('ur3/position', position, position_callback)
    sub_input = rospy.Subscriber('ur3/gripper_input', gripper_input, input_callback)

    # Check if ROS is ready for operation
    while(rospy.is_shutdown()):
        print("ROS is shutdown!")

    # Initialize the rate to publish to ur3/command
    loop_rate = rospy.Rate(SPIN_RATE)

    vel = 4.0
    accel = 4.0
    move_arm(pub_command, loop_rate, go_away, vel, accel)

    ic = ImageConverter(SPIN_RATE)
    time.sleep(5)

# ========================= Student's code starts here =========================

    #Z coordinate values
    PICK_Z  = 0.02
    PLACE_Z = 0.02

    rospy.loginfo("Waiting for block detection")

    #Waiting for initial detection and we are expecting 2 green and 2 yellow blocks
    while (len(xw_yw_G) == 0 and len(xw_yw_Y) == 0) and (len(xw_yw_G) != 2 and len(xw_yw_Y) != 2):
        time.sleep(0.1)

    #Save original positions of all 4 blocks
    original_green_blocks = []
    original_yellow_blocks = []

    def is_valid_coordinate(x, y):
        import math
        if math.isnan(x) or math.isnan(y):
            return False
        if abs(x) > 0.5 or abs(y) > 0.5:
            return False
        return True


    print("SAVING ORIGINAL BLOCK POSITIONS...")

    #Save initial green blocks (from first detection)
    for i, block_pos in enumerate(xw_yw_G):
        if i < 2 and is_valid_coordinate(block_pos[0], block_pos[1]):
            original_green_blocks.append([block_pos[0], block_pos[1], PICK_Z])
            print(f"Saved green block at: {block_pos}")

    #Save initial yellow blocks (from first detection)  
    for i, block_pos in enumerate(xw_yw_Y):
        if i < 2 and is_valid_coordinate(block_pos[0], block_pos[1]):
            original_yellow_blocks.append([block_pos[0], block_pos[1], PICK_Z])
            print(f"Saved yellow block at: {block_pos}")

    print(f"Original: {len(original_green_blocks)} green, {len(original_yellow_blocks)} yellow")

    #Goal positions
    green_goals = [[0.25, -0.10, PLACE_Z], [0.25, -0.20, PLACE_Z]]
    yellow_goals = [[0.25, 0.10, PLACE_Z], [0.25, 0.20, PLACE_Z]]

    #Move the green blocks from their original positions
    for i, green_block in enumerate(original_green_blocks):
        if i < len(green_goals):
            print(f"MOVING GREEN {i+1}: {green_block} -> {green_goals[i]}")
            error = move_block(pub_command, loop_rate, green_block, green_goals[i], vel, accel)
            if error == 0:
                print(f"Successfully moved green block {i+1}")
            time.sleep(2.0)

    #Move the yellow blocks from their original positions
    for i, yellow_block in enumerate(original_yellow_blocks):
        if i < len(yellow_goals):
            print(f"MOVING YELLOW {i+1}: {yellow_block} -> {yellow_goals[i]}")
            error = move_block(pub_command, loop_rate, yellow_block, yellow_goals[i], vel, accel)
            if error == 0:
                print(f"Successfully moved yellow block {i+1}")
            time.sleep(2.0)

# ========================= Student's code ends here ===========================

    move_arm(pub_command, loop_rate, go_away, vel, accel)
    rospy.loginfo("Task Completed!")
    print("Use Ctrl+C to exit program")
    rospy.spin()

if __name__ == '__main__':

    try:
        main()
    # When Ctrl+C is executed, it catches the exception
    except rospy.ROSInterruptException:
        pass
